### PR TITLE
Fixes #40 and #41

### LINKED ISSUE #40: Can't extract object when object key has a "folder
**Issue:**
When you have a blobname with a folder path in it and when you go to extract it, it can't find the file. The file gets downloaded to the tmp folder.

Example:
object = somefolder/apps/artifact.tar.gz

File gets download to `/tmp/build/23rfwef/artifact.tar.gz`, but when it goes to extract the file, it is looking for the file at `/tmp/build/23rfwef/somefolder/apps/artifact.tar.gz` which doesn't exist. 

**What should happen:**
File gets downloaded to /tmp/build/23rfwef/artifact.tar.gz and it extracts from the same place it's downloaded to.

**Solution:**
https://github.com/pivotal-cf/azure-blobstore-resource/blob/e7f086ccad6ffe1d7d586bfa595c738bd07968af/cmd/in/main.go#L77

blobName should be path.Base(blobName).

`err = in.UnpackBlob(filepath.Join(destinationDirectory, path.Base(blobName)))`

### PR DESCRIPTION
**Pull request by kungfoome**
Updated the unpack to use the base filename and not the entire path name
Added new case to unpack x-gzip which is equivalent to gzip

### CODE REVIEW

**Comment by christianang** [comment]
Thanks for the PR!

**Comment by kungfoome** [comment]
@christianang No problem. Thank for taking care of the pull request so quickly. Sorry, forgot to add the test case :/

**Comment by christianang** [comment]
No worries, it was quick enough to add. I have made a new release (v0.12.0) of the [image](https://github.com/pivotal-cf/azure-blobstore-resource/releases/tag/v0.12.0). If you are using latest or if you pin to v0.12.x you should be able to pick up these changes.

**Comment by kungfoome** [comment]
Awesome. we will give it a shot tomorrow. This will help a lot.

**Pull request merged**
